include:
- project: iiidevops-templates/ci-template
  ref: v2.11.0
  file: ci/template.gitlab-ci.yml

stages:
- initial
- scan
- build
- deploy
- test

Deploy--Elasticsearch:
  stage: deploy
  extends: .deploy-service
  variables:
    iiidevops: deploy-service
  script:
  - envsubst < k8s/es/kustomization.yaml.tmp > k8s/es/kustomization.yaml
  - envsubst < k8s/es/es-transformer.yaml.tmp > k8s/es/es-transformer.yaml
  - envsubst < k8s/import/kustomization.yaml.tmp > k8s/import/kustomization.yaml
  - envsubst < k8s/import/import-transformer.yaml.tmp > k8s/import/import-transformer.yaml
  - kubectl kustomize k8s/es/ | kubectl delete --ignore-not-found -f -
  - kubectl kustomize k8s/es/ | kubectl apply -f -
  - kubectl kustomize k8s/import/ | kubectl delete --ignore-not-found -f -
  - kubectl kustomize k8s/import/ | kubectl apply -f -

Deploy--Wait Elasticsearch:
  stage: deploy
  extends: .deploy-service
  image: iiiorg/iiidevops-cli:0.0.7
  variables:
    iiidevops: deploy-service
    max_wait: 128
    namespace: ${CI_PROJECT_NAME}
    deploy_name: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-es
  script:
  - deploy-wait.pl
