stages:
  - initial
  - scan
  - build
  - deploy
  - test

include:
  - project: 'iiidevops-templates/ci-template'
    ref: 'v2.1.1'
    file: 'ci/template.gitlab-ci.yml'

Deploy--Set environment and wait deployment:
  variables:
    iiidevops: deployed-environments
    max_wait: 128
    namespace: ${CI_PROJECT_NAME}
    deploy_name: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-es
  only:
    - master

Deploy--Elasticsearch:
  stage: deploy
  image:
    name: alpine/k8s:1.25.9
  variables:
    iiidevops: deployed-environments
  script:
  - envsubst < k8s/kustomization.yaml.tmp > k8s/kustomization.yaml
  - envsubst < k8s/es-transformer.yaml.tmp > k8s/es-transformer.yaml
  - envsubst < k8s/import-transformer.yaml.tmp > k8s/import-transformer.yaml
  - kubectl kustomize k8s/ | kubectl delete --ignore-not-found -f -
  - kubectl kustomize k8s/ | kubectl apply -f -
  only:
    - master


