apiVersion: batch/v1
kind: Job
metadata:
  name: import
  annotations:
    iiidevops.org/type: import-data
spec:
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      annotations:
        iiidevops.org/type: import-data
    spec:
      containers:
        - name: elasticsearch-import
          image: elasticdump/elasticsearch-dump
          imagePullPolicy: IfNotPresent
          # Ref - https://github.com/elasticsearch-dump/elasticsearch-dump
          command: ['sh', '-c', 'ls /mnt; ls /mnt/data; pwd; bash /mnt/import.sh ${repo_name} ${git_branch}']
          env:
          - name: repo_name
            valueFrom:
              configMapKeyRef:
                key: repo_name
                name: git
          - name: git_branch
            valueFrom:
              configMapKeyRef:
                key: git_branch
                name: git
          volumeMounts:
            - mountPath: /mnt
              name: initrepo
      initContainers:
        - name: clone-repo
          image: alpine/git
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - >-
              cd /mnt;
              export se="//";
              export url="${git_url/$se*/$se}${git_username}:${git_token}@${git_url/*$se}";
              git clone --branch ${git_branch} ${url} .;
              rm -rf .git;
              chmod -R 777 .;
          env:
          - name: git_url
            valueFrom:
              configMapKeyRef:
                key: git_url
                name: git
          - name: git_username
            valueFrom:
              configMapKeyRef:
                key: git_username
                name: git
          - name: git_token
            valueFrom:
              configMapKeyRef:
                key: git_token
                name: git
          - name: git_branch
            valueFrom:
              configMapKeyRef:
                key: git_branch
                name: git
          volumeMounts:
            - mountPath: /mnt
              name: initrepo
      # 暫時專案資料儲存區
      volumes:
        - name: initrepo
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 2