apiVersion: v1
kind: Service
metadata:
  name: es-svc
  labels: 
    app: es
  annotations:
    iiidevops.org/type: db-server
spec:
  type: NodePort
  selector:
    app: es
  ports:
    - name: es-tcp-9200
      protocol: TCP
      port: 9200
    - name: es-tcp-9300
      protocol: TCP
      port: 9300
